"use client";

import { FormEvent, useEffect, useState } from "react";
import { StudentApiError } from "../../../lib/studentApi";
import { firebaseErrorMessage, firebaseGoogleLogin, firebaseLogin } from "../../../lib/firebaseAuth";
import { safeReturnTo } from "../../../lib/authRedirect";

export default function StudentLoginPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [returnTo, setReturnTo] = useState("/student");
  useEffect(() => { const params = new URLSearchParams(window.location.search); const destination = safeReturnTo(params.get("returnTo")); setReturnTo(params.get("action") === "register" ? `${destination}${destination.includes("?") ? "&" : "?"}action=register` : destination); const reason = params.get("error"); if (reason === "google-account-conflict") setError("This email already uses email/password sign-in. Please use that method."); else if (reason === "google-failed") setError("Google sign-in could not be completed. Please try again."); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); const normalizedEmail = email.trim(); if (!normalizedEmail || !password) return setError("Email and password are required."); if (!/^\S+@\S+\.\S+$/.test(normalizedEmail)) return setError("Enter a valid email address."); setLoading(true); try { await firebaseLogin(normalizedEmail, password); window.location.href = returnTo; } catch (reason) { setError(reason instanceof StudentApiError ? reason.message : firebaseErrorMessage(reason)); } finally { setLoading(false); } }
  async function googleLogin() { setError(""); setLoading(true); try { await firebaseGoogleLogin(); window.location.href = returnTo; } catch (reason) { setError(reason instanceof StudentApiError ? reason.message : firebaseErrorMessage(reason)); } finally { setLoading(false); } }
  return <main className="student-login"><form className="student-login-box" onSubmit={submit}><div className="brand"><span className="brand-mark">CE</span><span>Campus Events</span></div><div className="eyebrow">Student access</div><h1 className="display">Sign in to continue.</h1><label className="field"><span>Email</span><input className="admin-key-input" type="email" placeholder="Enter your email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="field"><span>Password</span><div className="password-input-wrapper"><input className="admin-key-input" type={showPassword ? "text" : "password"} placeholder="Enter password" value={password} onChange={(event) => setPassword(event.target.value)} /><button type="button" className="password-visibility" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword((visible) => !visible)}>👁</button></div></label><div className="forgot-password-link"><a href="/student/forgot-password">Forgot password?</a></div>{error && <div className="admin-error">{error}</div>}<button className="btn" disabled={loading}>{loading ? "Signing in..." : "Login"}</button><button type="button" className="btn ghost" disabled={loading} onClick={() => void googleLogin()}>Continue with Google</button><p>Don&apos;t have an account? <a href="/student/signup">Sign up</a></p><button type="button" className="btn ghost" onClick={() => { window.location.href = "/"; }}>Back to explore</button></form></main>;
}