"use client";

import { useEffect, useState } from "react";
import { StudentEvent, studentFetch } from "../../../lib/studentApi";
import { StudentShell, formatStudentDate } from "../../../components/student/StudentShell";
import { getEventImageUrl } from "../../../lib/eventImage";

export default function StudentEventsPage() {
  const [events, setEvents] = useState<StudentEvent[]>([]); const [query, setQuery] = useState(""); const [category, setCategory] = useState(""); const [department, setDepartment] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const params = new URLSearchParams(); if (query) params.set("search", query); if (category) params.set("category", category); if (department) params.set("department", department); setLoading(true); studentFetch(`/api/events?${params}`).then(setEvents).catch((reason) => setError(reason instanceof Error ? reason.message : "Could not load events")).finally(() => setLoading(false)); }, [query, category, department]);
  return <StudentShell title="Find your next thing." subtitle="Browse published events across campus and reserve your place before registration closes."><div className="student-toolbar"><input className="search" placeholder="Search events..." value={query} onChange={(event) => setQuery(event.target.value)} /><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">All categories</option><option>Workshop</option><option>Competition</option><option>Hackathon</option><option>Cultural</option><option>Sports</option><option>Seminar</option></select><select value={department} onChange={(event) => setDepartment(event.target.value)}><option value="">All departments</option><option>Computer Science</option><option>Electronics</option><option>Management</option><option>Humanities</option><option>Mechanical</option></select></div>{error && <div className="admin-error">{error}</div>}{loading ? <div className="student-state">Loading published events...</div> : events.length === 0 ? <div className="student-state">No published events match your filters.</div> : <div className="event-grid">{events.map((event) => { const imageUrl = getEventImageUrl(event.poster ?? event.image ?? ""); return <article className="event-card" key={event._id}><div className="event-art" style={imageUrl ? { backgroundImage: `linear-gradient(135deg, rgba(14,24,22,0.2), rgba(14,24,22,0.7)), url("${imageUrl}")`, backgroundSize: "cover", backgroundPosition: "center" } : undefined}><span className="tag">{event.category}</span><span className="date-stamp">{new Date(event.date).getDate()}<small>{new Date(event.date).toLocaleString(undefined, { month: "short" }).toUpperCase()}</small></span></div><div className="card-body"><h3 className="display">{event.title}</h3><p>{event.description}</p><div className="meta"><span>{formatStudentDate(event.date)} · {event.venue}</span><b>{event.availableSeats} seats left</b></div><button className="btn" style={{ marginTop: 16 }} onClick={() => { window.location.href = `/student/events/${event._id}`; }}>View details</button></div></article>; })}</div>}</StudentShell>;
}