"use client";

import { FormEvent, useState } from "react";
import { StudentApiError } from "../../../lib/studentApi";
import { firebaseErrorMessage, firebaseSignup } from "../../../lib/firebaseAuth";

export default function StudentSignupPage() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [showConfirmPassword, setShowConfirmPassword] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (!name.trim() || !email.trim() || !password || !confirmPassword) return setError("Complete all required fields."); if (!/^\S+@\S+\.\S+$/.test(email)) return setError("Enter a valid email address."); if (password.length < 8) return setError("Password must be at least 8 characters."); if (password !== confirmPassword) return setError("Passwords do not match."); setLoading(true); try { await firebaseSignup(name, email, password); window.location.href = "/student"; } catch (reason) { setError(reason instanceof StudentApiError ? reason.message : firebaseErrorMessage(reason)); } finally { setLoading(false); } }
  return <main className="student-login"><form className="student-login-box" onSubmit={submit}><div className="brand"><span className="brand-mark">CE</span><span>Campus Events</span></div><div className="eyebrow">Create student account</div><h1 className="display">Join campus events.</h1><label className="field"><span>Full name</span><input className="admin-key-input" placeholder="Enter your full name" value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span>Email</span><input className="admin-key-input" type="email" placeholder="Enter your email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="field"><span>Password</span><div className="password-input-wrapper"><input className="admin-key-input" type={showPassword ? "text" : "password"} placeholder="Enter password" value={password} onChange={(event) => setPassword(event.target.value)} /><button type="button" className="password-visibility" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword((visible) => !visible)}>👁</button></div></label><label className="field"><span>Confirm password</span><div className="password-input-wrapper"><input className="admin-key-input" type={showConfirmPassword ? "text" : "password"} placeholder="Confirm password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} /><button type="button" className="password-visibility" aria-label={showConfirmPassword ? "Hide password" : "Show password"} onClick={() => setShowConfirmPassword((visible) => !visible)}>👁</button></div></label>{error && <div className="admin-error">{error}</div>}<button className="btn" disabled={loading}>{loading ? "Creating account..." : "Create account"}</button><p>Already have an account? <a href="/student/login">Sign in</a></p><button type="button" className="btn ghost" onClick={() => { window.location.href = "/"; }}>Back to explore</button></form></main>;
}